---
abstract: 'Automatically formats a text column with Textile, Markdown or BBCode.'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  version: 0.77
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-InflateColumn-Markup-Unified
requires:
  DBIx::Class: 0
  Markup::Unified: 0
  perl: 5.006
  version: 0.77
resources:
  homepage: http://github.com/ido50/DBIx-Class-InflateColumn-Markup-Unified/tree
  repository: git://github.com/ido50/DBIx-Class-InflateColumn-Markup-Unified.git
version: v0.21.1
